version: '3.8'
services:

  # TODO API
  api-todo:
    build: 
      context: api
      dockerfile: Dockerfile
    image: api.todo
    container_name: api.manabie.todo
    command: bash -c "make run"
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
    depends_on:
      postgresql:
        condition: service_healthy

  # Postgres
  postgresql:
    image: postgres:14.4
    container_name: postgresql.manabie.todo
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "todo"
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./init-database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
